### ISSUE TITLE
为什么想着爬人家的，而不是自己做呢？

### ISSUE THREAD

**Issue by chuxiaaaa** [Vikyanite/hidden-record-assistant#1]
GitHub里面有挺多开源项目的，像这种实现不难，你可以自己去找找

这个是我的项目，你也可以看看
https://gitee.com/chu_xia/lolbattle-query

**Comment by Vikyanite** [comment]
> GitHub里面有挺多开源项目的，像这种实现不难，你可以自己去找找
> 
> 这个是我的项目，你也可以看看 https://gitee.com/chu_xia/lolbattle-query

感谢您提出的issue，主要最开始知道能查隐藏战绩就是通过这个网页，有先入为主的行为，于是最开始就做的爬取网站返回数据了。了解到**LCUAPI**已经是写一半才发现的事情...不过想着做都做了，不如就做到底，会在第二版采用调用**LCUAPI**。

同时也非常感谢您分享的您的项目，相信在做第二版的时候，会对我提供非常大的帮助与思路参考。

Github上确实有比较多的类似的项目。不过我个人只是想做个小玩具，如果有人喜欢就会考虑根据他们的需求加入一点功能。同时在做的时候，了解一下关于现存的类似的小助手是怎么做出来的，算是一种学习与享受编程的乐趣。

再次感谢您提出的宝贵的issue☺

**Comment by boyback** [comment]
你这个101api一停就挂了

**Comment by Vikyanite** [comment]
> 你这个101api一停就挂了

您说的没有错，在近期已经遇到了这个问题，已经在最新分支[feat-wails](https://github.com/Vikyanite/hidden-record-assistant/tree/refactor-wails)中使用LCUAPI的方式加急解决，不过通过LCUAPI的方式需要先登录LOL客户端才能使用，也不知是否方便。

**Comment by Fanghua02** [comment]
因为不会
