### ISSUE TITLE
fyne不支持中文字体,中文字体需要同时打包。

### ISSUE THREAD

**Issue by limitcool** [Vikyanite/hidden-record-assistant#2]
如题,建议使用wails替代fyne.
![image](https://github.com/Vikyanite/hidden-record-assistant/assets/88604249/1704b0c1-d2b6-4842-b6bf-53bcaf377256)

**Comment by Vikyanite** [comment]
> 如题,建议使用wails替代fyne. ![image](https://user-images.githubusercontent.com/88604249/256992746-1704b0c1-d2b6-4842-b6bf-53bcaf377256.png)

感谢您提的issue，fyne对中文的支持不成熟确实让我非常头疼。最开始也考虑过使用Electron + Vue，不过因为我个人Vue掌握的不是很好，所以采用了最近有在学习的fyne来实现。目前的解决方案应该是会在项目里传入中文字体来解决乱码的问题。

您提到了Wails，我倒是孤陋寡闻没有听说过。我在接下来的几天将会去了解一下Wails，并会对其进行评估，如果Wails对于本项目来说更好我将会新建一个分支用Wails进行后续的开发。

非常感谢您宝贵的issue，让我学习到不少。

😊

**Comment by limitcool** [comment]
wails使用 Go 语言编写后端逻辑,提供丰富的 API 给前端调用,前端可以使用 Vue/React 等框架开发界面,编译成二进制文件,应用体积小,性能高,资源占用低,Electron是通过嵌入Chromium浏览器引擎和Node.js来实现的,所以它的应用本质上是一个浏览器环境。
而Wails不会嵌入整个浏览器,它使用系统的WebView组件来渲染UI,这类似一个轻量的浏览器引擎。
