### ISSUE TITLE
考虑用wails搞嘛

### ISSUE THREAD

**Issue by losanming** [Vikyanite/hidden-record-assistant#3]
fync做客户端不好看呀，到后面还得搞一些用户头像 英雄头像啥花里胡哨的东西，直接上wails

**Comment by Vikyanite** [comment]
感谢您的issue，采用wails已经在安排上了。fyne在实现一些我想要的效果的时候真的四处碰壁，只能说确实发展得不是很成熟。

目前我还在把fyne实现的第一版做完，然后还在学习前端相关知识。最近有点小忙，进度有点拖...

再次感谢您宝贵的建议！😊

**Comment by boyback** [comment]
我看你前端用vite生成了一个脚手架,没啥进度啊
